### ISSUE TITLE
Isolate can not be re-created on Arduino Yun (XMPP client problem)

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#26]
The cohorte.internal.forker isolate is present, however the isolate that hosts the application component is not created due to xmpp connection problem (see exceptions bellow). This application isolate is not re-created, the first isolate that we try to create is always looping trying to connect to the XMPP server.
 
Exception
````bash
2015-04-23 10:04:50,343:INFO    :herald.transports.xmpp.transport:event_thread_0 : Bot connected with JID: 8b55a012@charmanson.isandlatech.com (transport._on_session_start() @296)
2015-04-23 10:05:50,774:INFO    :herald.transports.xmpp.transport:read_thread    : End of session (transport._on_session_end() @348)
2015-04-23 10:05:59,985:WARNING :sleekxmpp.xmlstream.cert:read_thread    : Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED. (cert.verify() @138)
2015-04-23 10:06:00,801:WARNING :sleekxmpp.xmlstream.cert:event_thread_0 : Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED. (cert.extract_dates() @102)
2015-04-23 10:06:30,909:WARNING :sleekxmpp.xmlstream.handler.waiter:event_thread_0 : Timed out waiting for IqWait_89c7f6f2-6f9d-418e-9691-13fa5f860322-1F4 (waiter.wait() @77)
2015-04-23 10:06:30,937:ERROR   :sleekxmpp.xmlstream.xmlstream:event_thread_0 : Error processing event handler: <bound method HeraldBot.on_session_start of <herald.transports.xmpp.bot.HeraldBot object at 0x7632dfb0>> (xmlstream._event_runner() @1702)
Traceback (most recent call last):
  File "/root/cohorte_home/repo/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/root/cohorte_home/repo/pelix/misc/xmpp.py", line 111, in on_session_start
    self.get_roster()
  File "/root/cohorte_home/repo/sleekxmpp/clientxmpp.py", line 258, in get_roster
    response = iq.send(block, timeout, callback)
  File "/root/cohorte_home/repo/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
IqTimeout
2015-04-23 10:06:30,982:ERROR   :sleekxmpp.basexmpp  :event_thread_0 : Request timed out: <iq type="get" id="89c7f6f2-6f9d-418e-9691-13fa5f860322-1F4"><query xmlns="jabber:iq:roster" /></iq> (basexmpp.exception() @804)
2015-04-23 10:06:31,032:WARNING :sleekxmpp.basexmpp  :event_thread_0 : You should catch IqTimeout exceptions (basexmpp.exception() @805)
2015-04-23 10:06:31,045:INFO    :herald.transports.xmpp.transport:event_thread_0 : Bot connected with JID: e4b35b51@charmanson.isandlatech.com (transport._on_session_start() @296)
2015-04-23 10:07:31,824:INFO    :herald.transports.xmpp.transport:read_thread    : End of session (transport._on_session_end() @348)
2015-04-23 10:07:40,940:WARNING :sleekxmpp.xmlstream.cert:read_thread    : Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED. (cert.verify() @138)
2015-04-23 10:07:41,741:WARNING :sleekxmpp.xmlstream.cert:event_thread_0 : Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED. (cert.extract_dates() @102)
2015-04-23 10:08:11,848:WARNING :sleekxmpp.xmlstream.handler.waiter:event_thread_0 : Timed out waiting for IqWait_89c7f6f2-6f9d-418e-9691-13fa5f860322-1F7 (waiter.wait() @77)
2015-04-23 10:08:11,882:ERROR   :sleekxmpp.xmlstream.xmlstream:event_thread_0 : Error processing event handler: <bound method HeraldBot.on_session_start of <herald.transports.xmpp.bot.HeraldBot object at 0x7632dfb0>> (xmlstream._event_runner() @1702)
Traceback (most recent call last):
  File "/root/cohorte_home/repo/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/root/cohorte_home/repo/pelix/misc/xmpp.py", line 111, in on_session_start
    self.get_roster()
  File "/root/cohorte_home/repo/sleekxmpp/clientxmpp.py", line 258, in get_roster
    response = iq.send(block, timeout, callback)
  File "/root/cohorte_home/repo/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
IqTimeout
2015-04-23 10:08:11,929:ERROR   :sleekxmpp.basexmpp  :event_thread_0 : Request timed out: <iq type="get" id="89c7f6f2-6f9d-418e-9691-13fa5f860322-1F7"><query xmlns="jabber:iq:roster" /></iq> (basexmpp.exception() @804)
2015-04-23 10:08:11,957:WARNING :sleekxmpp.basexmpp  :event_thread_0 : You should catch IqTimeout exceptions (basexmpp.exception() @805)
2015-04-23 10:08:11,986:INFO    :herald.transports.xmpp.transport:event_thread_0 : Bot connected with JID: a395cf6e@charmanson.isandlatech.com (transport._on_session_start() @296)
2015-04-23 10:09:12,205:INFO    :herald.transports.xmpp.transport:read_thread    : End of session (transport._on_session_end() @348)
2015-04-23 10:09:19,826:WARNING :sleekxmpp.xmlstream.cert:read_thread    : Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED. (cert.verify() @138)
2015-04-23 10:09:20,761:WARNING :sleekxmpp.xmlstream.cert:event_thread_0 : Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED. (cert.extract_dates() @102)
2015-04-23 10:09:50,907:WARNING :sleekxmpp.xmlstream.handler.waiter:event_thread_0 : Timed out waiting for IqWait_89c7f6f2-6f9d-418e-9691-13fa5f860322-1FA (waiter.wait() @77)
2015-04-23 10:09:50,935:ERROR   :sleekxmpp.xmlstream.xmlstream:event_thread_0 : Error processing event handler: <bound method HeraldBot.on_session_start of <herald.transports.xmpp.bot.HeraldBot object at 0x7632dfb0>> (xmlstream._event_runner() @1702)
Traceback (most recent call last):
  File "/root/cohorte_home/repo/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/root/cohorte_home/repo/pelix/misc/xmpp.py", line 111, in on_session_start
    self.get_roster()
  File "/root/cohorte_home/repo/sleekxmpp/clientxmpp.py", line 258, in get_roster
    response = iq.send(block, timeout, callback)
  File "/root/cohorte_home/repo/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
IqTimeout
2015-04-23 10:09:50,982:ERROR   :sleekxmpp.basexmpp  :event_thread_0 : Request timed out: <iq type="get" id="89c7f6f2-6f9d-418e-9691-13fa5f860322-1FA"><query xmlns="jabber:iq:roster" /></iq> (basexmpp.exception() @804)
2015-04-23 10:09:51,020:WARNING :sleekxmpp.basexmpp  :event_thread_0 : You should catch IqTimeout exceptions (basexmpp.exception() @805)
2015-04-23 10:09:51,034:INFO    :herald.transports.xmpp.transport:event_thread_0 : Bot connected with JID: d3ad7221@charmanson.isandlatech.com (transport._on_session_start() @296)
````

**Comment by debbabi** [comment]
default iqTimeout is set to be 30 seconds!

https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/xmlstream/xmlstream.py#L49

**Comment by debbabi** [comment]
See https://github.com/isandlaTech/cohorte-platforms/issues/20

**Comment by debbabi** [comment]
Seems to be ok now
