### ISSUE TITLE
Exception when stopping a node (v 1.0.1.dev)

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#35]
(1)
``````
2015-05-26 10:47:49,947:WARNING:IOWatcher-Notify    : Thread IOWatcher-Notify-0 is still alive...
2015-05-26 10:47:51,880:ERROR:cohorte.forker.watchers: Error notifying listener: 'NoneType' object has no attribute 'normalize'
Traceback (most recent call last):
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/forker/watchers.py", line 153, in _notify_listeners
    listener.handle_lost_isolate(uid, name)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/composer/node/composer.py", line 484, in handle_lost_isolate
    self.instantiate(lost)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/composer/node/composer.py", line 309, in instantiate
    bundles = self._compute_bundles(components)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/composer/node/composer.py", line 209, in _compute_bundles
    bundles[component] = self._finder.normalize(component)
AttributeError: 'NoneType' object has no attribute 'normalize'
``````

(2)
`````
2015-05-26 10:57:18,590:CRITICAL:cohorte.monitor.basic: >>> PLATFORM STOPPING <<<
Exception in thread platform-stop:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/monitor/basic.py", line 420, in _stop_platform
    self._forker.stop_isolate(uid)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/forker/basic.py", line 274, in stop_isolate
    starter = self._isolates.pop(uid)
KeyError: '950d84b3-b2f0-47a4-aa61-23c6df34803f'
`````

(3) 
`````
$ Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/bin/scripts/cohorte-start-node.py", line 533, in <module>
    sys.exit(main())
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/bin/scripts/cohorte-start-node.py", line 519, in main
    p.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1565, in wait
    (pid, sts) = self._try_wait(0)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1513, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
`````

(4) Subprocess is not killed when exceptions occured when stopping the node!

**Comment by debbabi** [comment]
Also,

`````
2015-05-26 10:57:18,590:CRITICAL:cohorte.monitor.basic: >>> PLATFORM STOPPING <<<
Exception in thread platform-stop:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/monitor/basic.py", line 420, in _stop_platform
    self._forker.stop_isolate(uid)
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/repo/cohorte/forker/basic.py", line 274, in stop_isolate
    starter = self._isolates.pop(uid)
KeyError: '950d84b3-b2f0-47a4-aa61-23c6df34803f'
`````

**Comment by debbabi** [comment]
When stopped using Ctrl+C
$ Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/bin/scripts/cohorte-start-node.py", line 533, in <module>
    sys.exit(main())
  File "/Users/debbabi/OneDrive/Workspaces_Git/COHORTE/cohorte-platforms/bin/scripts/cohorte-start-node.py", line 519, in main
    p.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1565, in wait
    (pid, sts) = self._try_wait(0)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1513, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
