### ISSUE TITLE
In CLOUD LED demo, devices could be disconnect / reconnected to XMPP server but could not joind rooms again

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#43]
Here is the log from the raspberry device : 

`````
2015-07-09 12:10:58,911:ERROR   :sleekxmpp.xmlstream.xmlstream:read_thread    : Socket Error #104: Connection reset by peer (xmlstream._process() @1496)
2015-07-09 12:10:58,913:INFO    :herald.transports.xmpp.transport:read_thread    : End of session (transport._on_session_end() @504)
2015-07-09 12:10:58,916:WARNING :sleekxmpp.xmlstream.xmlstream:read_thread    : Failed to send </stream:stream> (xmlstream.send_raw() @1342)
2015-07-09 12:10:58,918:INFO    :herald.transports.xmpp.transport:read_thread    : End of session (transport._on_session_end() @504)
2015-07-09 12:11:02,921:ERROR   :sleekxmpp.xmlstream.xmlstream:read_thread    : Hanged threads: [<_MainThread(MainThread, started 1995816960)>, <Thread(RemoteShell-0, started daemon 1952445552)>, <Thread(HttpService-50535-Server, started daemon 1970664560)>, <LoopTimer(Herald-GC, started daemon 1979053168)>, <Thread(Herald-XMPP-SendThread-0, started daemon 1962275952)>, <Thread(HeraldNotify-4932, started daemon 1902113904)>, <Thread(event_thread_0, started 1944056944)>, <Thread(read_thread, started 1918891120)>] (xmlstream._wait_for_threads() @1403)
2015-07-09 12:11:02,922:ERROR   :sleekxmpp.xmlstream.xmlstream:read_thread    : This may be due to calling disconnect() from a non-threaded event handler. Be sure that event handlers that call disconnect() are registered using: add_event_handler(..., threaded=True) (xmlstream._wait_for_threads() @1408)
2015-07-09 12:11:02,925:WARNING :herald.transports.xmpp.transport:read_thread    : Bot disconnected: reconnect (state=created) (transport._on_disconnected() @557)
2015-07-09 12:11:02,927:INFO    :herald.transports.xmpp.transport:read_thread    : changing XMPP bot state to : destroying (transport.__destroy_bot() @271)
2015-07-09 12:11:02,995:INFO    :herald.transports.xmpp.transport:Herald-DestroyBot: changing XMPP bot state to : destroyed (transport._destroy_bot() @305)
2015-07-09 12:11:03,001:ERROR   :InstanceManager-cohorte-isolate-agent:Herald-Unbind  : Component 'cohorte-isolate-agent': error calling callback method for event INVALIDATE (instance.safe_callback() @555)
Traceback (most recent call last):
  File "/home/pi/cohorte/dist/cohorte/repo/pelix/ipopo/instance.py", line 534, in safe_callback
    return self.__callback(event, *args, **kwargs)
  File "/home/pi/cohorte/dist/cohorte/repo/pelix/ipopo/instance.py", line 484, in __callback
    result = comp_callback(self.instance, *args, **kwargs)
  File "/home/pi/cohorte/dist/cohorte/repo/cohorte/monitor/agent.py", line 155, in invalidate
    self._sender.fire_group('monitors', message)
  File "/home/pi/cohorte/dist/cohorte/repo/herald/core.py", line 714, in fire_group
    "No transport bound yet.")
NoTransport: No transport bound yet.
2015-07-09 12:11:03,028:INFO    :debug.agent         :Herald-Unbind  : Debug agent Gone (agent.invalidate() @501)
2015-07-09 12:11:03,931:INFO    :herald.transports.xmpp.transport:Thread-1       : changing XMPP bot state to : creating (transport.__create_new_bot() @176)
2015-07-09 12:11:04,711:WARNING :sleekxmpp.xmlstream.cert:read_thread    : Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED. (cert.verify() @138)
2015-07-09 12:11:05,024:WARNING :sleekxmpp.xmlstream.cert:event_thread_0 : Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED. (cert.extract_dates() @102)
2015-07-09 12:11:05,196:INFO    :herald.transports.xmpp.transport:event_thread_0 : Bot connected with JID: fe8f5989@charmanson.isandlatech.com (transport._on_session_start() @444)
2015-07-09 12:11:05,283:ERROR   :herald.transports.xmpp.transport:event_thread_0 : Error creating room:  (conflict) (transport.__room_error() @429)
2015-07-09 12:11:05,340:ERROR   :herald.transports.xmpp.transport:event_thread_0 : Error creating room:  (conflict) (transport.__room_error() @429)
2015-07-09 12:11:05,368:ERROR   :herald.transports.xmpp.transport:event_thread_0 : Error creating room:  (conflict) (transport.__room_error() @429)
2015-07-09 12:11:05,382:ERROR   :herald.transports.xmpp.transport:event_thread_0 : Error creating room:  (conflict) (transport.__room_error() @429)
2015-07-09 12:11:05,394:ERROR   :herald.transports.xmpp.transport:event_thread_0 : Error joining rooms: cohorte-led-bluemix--led-raspberry-python-auto01@conference.charmanson.isandlatech.com, cohorte-led-bluemix--0b206bb4-e66f-4ad8-b311-965077052c79@conference.charmanson.isandlatech.com, cohorte-led-bluemix--led-raspberry@conference.charmanson.isandlatech.com, cohorte-led-bluemix@conference.charmanson.isandlatech.com, cohorte-led-bluemix--all@conference.charmanson.isandlatech.com (transport.__on_ready() @472)
2015-07-09 12:11:05,399:INFO    :herald.transports.xmpp.transport:event_thread_0 : XMPP transport service activated (transport.__on_ready() @488)
2015-07-09 12:11:05,400:INFO    :herald.transports.xmpp.transport:event_thread_0 : changing XMPP bot state to : created (transport.__on_ready() @490)
2015-07-09 12:11:05,402:INFO    :cohorte.monitor.agent:Herald-Bind    : Isolate agent validated (agent.validate() @146)
2015-07-09 12:11:05,425:INFO    :cohorte.monitor.agent:Herald-Bind    : Monitors notified of isolate readiness (agent.peer_registered() @122)
2015-07-09 12:11:05,421:ERROR   :herald.transports.xmpp.transport:event_thread_0 : Error creating room:  (conflict) (transport.__room_error() @429)
2015-07-09 12:11:05,564:INFO    :debug.agent         :Herald-Bind    : Debug agent Ready (agent.validate() @490)
2015-07-09 12:11:06,930:ERROR   :sleekxmpp.xmlstream.xmlstream:read_thread    : Hanged threads: [<_MainThread(MainThread, started 1995816960)>, <Thread(RemoteShell-0, started daemon 1952445552)>, <Thread(HttpService-50535-Server, started daemon 1970664560)>, <Thread(event_thread_0, started 1935668336)>, <LoopTimer(Herald-GC, started daemon 1979053168)>, <Thread(send_thread, started 1987441776)>, <Thread(HeraldNotify-4932, started daemon 1902113904)>, <Thread(scheduler_thread, started 1910502512)>, <Thread(read_thread, started 1891628144)>, <Thread(event_thread_0, started 1944056944)>, <Thread(read_thread, started 1918891120)>, <Thread(Herald-XMPP-SendThread-1, started daemon 1927279728)>] (xmlstream._wait_for_threads() @1403)
2015-07-09 12:11:06,936:ERROR   :sleekxmpp.xmlstream.xmlstream:read_thread    : This may be due to calling disconnect() from a non-threaded event handler. Be sure that event handlers that call disconnect() are registered using: add_event_handler(..., threaded=True) (xmlstream._wait_for_threads() @1408)
`````

**Comment by debbabi** [comment]
exception protected in https://github.com/isandlaTech/cohorte-runtime/commit/3f1ae39484f1e23c9f81a319f28d7e8c72ef889f
