### ISSUE TITLE
cohorte-update cannot delete old distribution

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#52]
Log:
`````
-----------------[ Installed COHORTE distribution ]--------------------

    - distribution : cohorte-macosx-distribution
    - version      : 1.1.1
    - stage        : dev
    - timestamp    : 20150807-152217
    - location     : /Users/ogattaz/workspaces/AgilimNGServer/cohorte-home

-----------------------------------------------------------------------

[INFO] getting latest cohorte-macosx-distribution info (from internet)...

    +-----------+-----------------+-----------------+-----------------+
    |           | ACTUAL          | LATEST DEV      | LATEST RELEASE  |
    +-----------+-----------------+-----------------+-----------------+
    | version   | 1.1.1           | 1.1.1           | 1.1.0           |
    +-----------+-----------------+-----------------+-----------------+    
    | stage     | dev             | dev             | release         |    
    +-----------+-----------------+-----------------+-----------------+    
    | timestamp | 20150807-152217 | 20150812-010232 | 20150713-152831 |
    +-----------+-----------------+-----------------+-----------------+

[INFO] There is a new 'development' version!
     | Would you like to install it (yes/no)? or show its changelog (log)? yes

[INFO] downloading cohorte-macosx-distribution-1.1.1-20150812-010232 (dev) ...
     | total file size to download ~ 10Mb
     | Progress: [###############] 100%
     | Done.

[INFO] archiving actual distribution ...
     | Done.
     | you can rollback using --roll-back option.

[INFO] deleting actual distribution ...
Traceback (most recent call last):
  File "/Users/ogattaz/workspaces/AgilimNGServer/cohorte-home/bin/scripts/cohorte-update.py", line 407, in <module>
    sys.exit(main())
  File "/Users/ogattaz/workspaces/AgilimNGServer/cohorte-home/bin/scripts/cohorte-update.py", line 397, in main
    return update(latest_dev)
  File "/Users/ogattaz/workspaces/AgilimNGServer/cohorte-home/bin/scripts/cohorte-update.py", line 152, in update
    remove_actual_dist()            
  File "/Users/ogattaz/workspaces/AgilimNGServer/cohorte-home/bin/scripts/cohorte-update.py", line 296, in remove_actual_dist
    os.rmdir(os.path.join(root, name))
OSError: [Errno 66] Directory not empty: '/Users/ogattaz/workspaces/AgilimNGServer/cohorte-home/.archive/cohorte/bin/scripts'
`````

**Comment by tcalmant** [comment]
This can corrected by using [``shutil.rmtree``](https://docs.python.org/2/library/shutil.html#shutil.rmtree) instead of ``os.rmdir``.

**Comment by debbabi** [comment]
WARNING: .../bin/scripts/cohorte-update.py: invalid token (cohorte-update.py, line 212)
