### ISSUE TITLE
Exception while stopping a Node

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#54]
Should protect against NoneType exception.

```
Exception in thread node-stop:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/debbabi/Downloads/cohorte-1.1_5.0/repo/cohorte/monitor/basic.py", line 442, in _stop_node
    self._composer.set_platform_stopping()
AttributeError: 'NoneType' object has no attribute 'set_platform_stopping'
```

**Comment by debbabi** [comment]
We also lose `stdin` in several cases!
