### ISSUE TITLE
Shutdown exceptions

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#8]
Some exceptions are captured while stopping Cohorte. We will trace them in comments of this issue to correct them in the next release.

**Comment by debbabi** [comment]
Cohorte 1.0.0 Linux 64 bits
Isolate threads are not killed

LOG :
2015-01-20 17:13:10,226:ERROR:forker-core-killer  : Error executing stop: '82377306-915d-45ce-9068-75e2fd4be1a5'
Traceback (most recent call last):
  File "/home/isandlatech/cohorte/dist/cohorte-1.0.0/repo/pelix/threadpool.py", line 397, in __run
    future.execute(method, args, kwargs)
  File "/home/isandlatech/cohorte/dist/cohorte-1.0.0/repo/pelix/threadpool.py", line 119, in execute
    result = method(*args, **kwargs)
  File "/home/isandlatech/cohorte/dist/cohorte-1.0.0/repo/cohorte/forker/starters/cohorte_boot.py", line 221, in stop
    uid, beans.Message(cohorte.monitor.SIGNAL_STOP_ISOLATE))
  File "/home/isandlatech/cohorte/dist/cohorte-1.0.0/repo/herald/core.py", line 594, in fire
    peer = self._directory.get_peer(target)
  File "/home/isandlatech/cohorte/dist/cohorte-1.0.0/repo/herald/directory.py", line 320, in get_peer
    return self._peers[uid]
KeyError: '82377306-915d-45ce-9068-75e2fd4be1a5'
